export const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#0a0a0a",
    color: "#e5e5e5",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 1000,
    borderBottom: "1px solid #262626",
    backgroundColor: "rgba(10,10,10,0.92)",
    backdropFilter: "blur(10px)",
  },
  headerInner: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "24px",
  },
  brand: {
    color: "#f5f5f5",
    textDecoration: "none",
    fontSize: "14px",
    letterSpacing: "0.02em",
  },
  nav: {
    display: "flex",
    gap: "20px",
    flexWrap: "wrap",
  },
  navLink: {
    color: "#a3a3a3",
    textDecoration: "none",
    fontSize: "14px",
  },
  main: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "56px 24px 80px",
  },
  hero: {
    display: "grid",
    gridTemplateColumns: "1.6fr 1fr",
    gap: "40px",
    paddingBottom: "64px",
    borderBottom: "1px solid #171717",
  },
  kicker: {
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.25em",
    color: "#22d3ee",
    marginBottom: "16px",
  },
  title: {
    fontSize: "54px",
    lineHeight: 1.1,
    fontWeight: 300,
    color: "#fafafa",
    margin: 0,
    maxWidth: "760px",
  },
  lead: {
    marginTop: "24px",
    fontSize: "18px",
    lineHeight: 1.8,
    color: "#a3a3a3",
    maxWidth: "760px",
  },
  buttonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "16px",
    marginTop: "28px",
  },
  primaryButton: {
    padding: "12px 20px",
    border: "1px solid rgba(34,211,238,0.4)",
    borderRadius: "16px",
    color: "#67e8f9",
    textDecoration: "none",
    display: "inline-block",
  },
  secondaryButton: {
    padding: "12px 20px",
    border: "1px solid #262626",
    borderRadius: "16px",
    color: "#d4d4d4",
    textDecoration: "none",
    display: "inline-block",
  },
  sideCard: {
    border: "1px solid #262626",
    borderRadius: "24px",
    padding: "24px",
    backgroundColor: "rgba(23,23,23,0.55)",
    display: "flex",
    flexDirection: "column",
    gap: "28px",
  },
  sideTitle: {
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    color: "#737373",
    marginBottom: "8px",
  },
  sideText: {
    color: "#d4d4d4",
    fontSize: "14px",
    lineHeight: 1.8,
    margin: 0,
  },
  section: {
    padding: "64px 0",
    borderBottom: "1px solid #171717",
  },
  sectionSplit: {
    display: "grid",
    gridTemplateColumns: "0.9fr 1.1fr",
    gap: "40px",
    padding: "64px 0",
    borderBottom: "1px solid #171717",
  },
  sectionTitle: {
    fontSize: "36px",
    lineHeight: 1.2,
    fontWeight: 300,
    color: "#fafafa",
    margin: 0,
  },
  paragraph: {
    color: "#a3a3a3",
    lineHeight: 1.9,
    fontSize: "16px",
    marginTop: 0,
    marginBottom: "18px",
  },
  mutedText: {
    color: "#737373",
    fontSize: "14px",
    lineHeight: 1.8,
    maxWidth: "420px",
    textAlign: "right",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  card: {
    border: "1px solid #262626",
    borderRadius: "24px",
    padding: "24px",
    backgroundColor: "rgba(23,23,23,0.45)",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "24px",
  },
  cardTag: {
    color: "#22d3ee",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    margin: 0,
  },
  cardTitle: {
    marginTop: "10px",
    marginBottom: "14px",
    fontSize: "28px",
    fontWeight: 300,
    color: "#f5f5f5",
  },
  cardText: {
    color: "#a3a3a3",
    lineHeight: 1.8,
    fontSize: "16px",
    margin: 0,
  },
  cardYear: {
    color: "#737373",
    fontSize: "14px",
    whiteSpace: "nowrap",
  },
  timeline: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
  },
  timelineItem: {
    display: "grid",
    gridTemplateColumns: "110px 1fr",
    gap: "16px",
  },
  timelinePeriod: {
    color: "#737373",
    fontSize: "14px",
  },
  timelineTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: 400,
    color: "#f5f5f5",
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  tag: {
    border: "1px solid #262626",
    borderRadius: "999px",
    padding: "10px 16px",
    backgroundColor: "rgba(23,23,23,0.6)",
    color: "#d4d4d4",
    fontSize: "14px",
  },
};